;; -*- lexical-binding: t; -*-

(defun vhdl-slv->unsigned ()
  (interactive)
  (er/mark-symbol)
  (let ((sig (buffer-substring-no-properties (mark) (point))))
    (delete-region (mark) (point))
    (insert (format  "unsigned(%s)" sig))
    (backward-char 1)))

(defun vhdl-unsigned->slv ()
  (interactive)
  (er/mark-symbol)
  (let ((sig (buffer-substring-no-properties (mark) (point))))
    (delete-region (mark) (point))
    (insert (format  "std_logic_vector(%s)" sig))
    (backward-char 1)))

(defun vhdl-int->slv ()
  (interactive)
  (er/mark-symbol)
  (let ((sig (buffer-substring-no-properties (mark) (point))))
    (delete-region (mark) (point))
    (insert (format  "std_logic_vector(to_unsigned(%s, ))" sig))
    (backward-char 2)))

(defun vhdl-slv->int ()
  (interactive)
  (er/mark-symbol)
  (let ((sig (buffer-substring-no-properties (mark) (point))))
    (delete-region (mark) (point))
    (insert (format  "to_integer(unsigned(%s))" sig))))
