;;; loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from my-autoloads/gpt.el

(autoload 'gpt-prompt "my-autoloads/gpt" "\
Dear AI, I want to do something on the selected text." t)
(autoload 'gpt-inline "my-autoloads/gpt" "\
Dear AI, do something and be concise." t)
(autoload 'gpt-debug "my-autoloads/gpt" "\
Dear AI, help me debug please!!" t)
(autoload 'gpt-writing "my-autoloads/gpt" "\
Dear AI, improve my writing please!!" t)
(autoload 'gpt-grammar "my-autoloads/gpt" "\
Dear AI, correct my grammar please!!" t)
(autoload 'gpt-doc "my-autoloads/gpt" "\
Dear AI, write some documentation please!!" t)
(autoload 'gpt-docstring "my-autoloads/gpt" "\
Dear AI, write a docstring please!!" t)
(autoload 'gpt-suggest "my-autoloads/gpt" "\
Dear AI, make suggestions please!!" t)
(autoload 'gpt-improve "my-autoloads/gpt" "\
Dear AI, improve please!!" t)
(autoload 'gpt-help "my-autoloads/gpt" "\
Dear AI, help please!!" t)
(autoload 'gpt-refactor "my-autoloads/gpt" "\
Dear AI, refactor please!!" t)
(register-definition-prefixes "my-autoloads/gpt" '("gpt-"))


;;; Generated autoloads from my-autoloads/my-defuns.el

(autoload 'emacs-lsp-booster-install "my-autoloads/my-defuns" "\
Install LSP booster with cargo." t)
(autoload 'my/toggle-c-verilog-comment-style "my-autoloads/my-defuns" nil t)
(autoload 'my/describe-char-at-mouse-click "my-autoloads/my-defuns" "\
`describe-char' at CLICK-EVENT's position.
CLICK-EVENT should be a mouse-click event.

From https://emacs.stackexchange.com/questions/303/describe-face-character-not-under-unreachable-by-the-cursor

(fn CLICK-EVENT)" t)
(autoload 'verilog-name-to-port-inst "my-autoloads/my-defuns" "\
Convert symbol at point into a verilog port instantiation.

e.g. if you place the point at `outcome_cycle_idx_0' in the
following line and execute this function:

output reg [TBINB-1:0]       outcome_cycle_idx_0,

it will be transformed into:

.outcome_cycle_idx_0 (outcome_cycle_idx_0)


This makes for easy conversion of some port list or wire list
into Verilog ports." t)
(autoload 'vhdl-unsigned->slv "my-autoloads/my-defuns" "\
Convert a VHDL unsigned to standard logic vector." t)
(autoload 'vhdl-int->slv "my-autoloads/my-defuns" "\
Convert a VHDL integer to standard logic vector." t)
(autoload 'vhdl-slv->int "my-autoloads/my-defuns" "\
Convert a VHDL standard logic vector to integer." t)
(autoload 'vhdl-slv->unsigned "my-autoloads/my-defuns" "\
Convert a VHDL standard logic vector to unsigned." t)
(autoload 'yosys-make-schematic "my-autoloads/my-defuns" "\
Make a yosys schematic from the module at point. " t)
(autoload 'rainbow-delimiters--apply-color-range "my-autoloads/my-defuns" "\
Highlight a single delimiter at LOC according to DEPTH.

LOC is the location of the character to add text properties to.
DEPTH is the nested depth at LOC, which determines the face to use.
MATCH is nil iff it's a mismatched closing delimiter.

(fn START END DEPTH MATCH)")
(autoload 'rainbow-delimiters--propertize-verilog "my-autoloads/my-defuns" "\
Highlight delimiters in region between point and END.

Used by font-lock for dynamic highlighting.

(fn _)" t)
(autoload 'set-font-interactive "my-autoloads/my-defuns" "\
Interactively choose and set a font." t)
(autoload 'synchronize-theme "my-autoloads/my-defuns" nil t)
(autoload 'set-dark-mode "my-autoloads/my-defuns" "\
Set the color scheme to be dark." t)
(autoload 'set-light-mode "my-autoloads/my-defuns" "\
Set the color scheme to be light." t)
(autoload 'set-auto-dark-mode "my-autoloads/my-defuns" "\
Set the color scheme to follow the day cycle (roughly)." t)
(autoload 'toggle-dark-mode "my-autoloads/my-defuns" "\
Toggle dark mode." t)
(autoload 'home-manager-switch "my-autoloads/my-defuns" "\
Reload home manager configuration." t)
(autoload 'home-manager-update "my-autoloads/my-defuns" "\
Reload home manager configuration." t)
(autoload 'project-root-dir "my-autoloads/my-defuns" "\
Return root directory of current project.

(fn &rest _)")
(autoload 'projectile-project-root "my-autoloads/my-defuns" "\
Get the root of the current VCS project.

(fn &rest _)")
(autoload 'doom-project-root "my-autoloads/my-defuns" "\
Get the root of the current VCS project.

(fn &rest _)")
(autoload 'sudo-shell-command "my-autoloads/my-defuns" "\


(fn COMMAND)")
(autoload 'xclip "my-autoloads/my-defuns" "\
" t)
(autoload 'copy-file-name-to-kill "my-autoloads/my-defuns" "\
Copy the current buffer file name to the clipboard." t)
(autoload 'make-declare "my-autoloads/my-defuns" "\
Make a function declaration from the symbol at point." t)
(autoload 'scratch-new "my-autoloads/my-defuns" "\
Create a new empty scratch buffer." t)
(autoload 'byte-compile-config "my-autoloads/my-defuns" nil t)
(autoload 'open-link-or "my-autoloads/my-defuns" "\


(fn FN)")
(autoload 're-indent-buffer "my-autoloads/my-defuns" nil t)
(autoload 'ap/tab-fallthrough "my-autoloads/my-defuns" nil t)
(defvar preferred-terminal 'wezterm "\
Default terminal used by `open-pwd-in-terminal'")
(autoload 'open-pwd-in-terminal "my-autoloads/my-defuns" "\
Opens the present working directory in external terminal." t)
(autoload 'run-in-terminal "my-autoloads/my-defuns" "\


(fn CMD)")
(autoload 'open-buffer-in-vim "my-autoloads/my-defuns" "\
Opens the current buffer in gvim." t)
(autoload 'org-make-tables-pretty "my-autoloads/my-defuns" "\
Makes org mode tables pretty in the current buffer." t)
(autoload 'xdg-do "my-autoloads/my-defuns" "\


(fn X)")
(autoload 'xdg-browse-directory "my-autoloads/my-defuns" "\
Open the current file's directory however the OS would." t)
(autoload 'xdg-open-file "my-autoloads/my-defuns" "\
Open the current file however the OS would." t)
(autoload 'file-clipboard-copy "my-autoloads/my-defuns" "\
Copy currently opened file to clipboard." t)
(autoload 'py-black "my-autoloads/my-defuns" "\
Format python file with black." t)
(autoload 'autopep "my-autoloads/my-defuns" "\
Format python file with autopep." t)
(autoload 'verible-format "my-autoloads/my-defuns" "\
Format verilog file with verible." t)
(autoload 'pyment "my-autoloads/my-defuns" "\
Format python file with pyment" t)
(autoload 'switch-to-previous-buffer "my-autoloads/my-defuns" "\
Switch to previously open buffer. Repeated invocations toggle
between the two most recently open buffers." t)
(autoload 'open-todo "my-autoloads/my-defuns" "\
Open my todo file" t)
(autoload 'org-agenda-and-todo "my-autoloads/my-defuns" "\
Open the full org agenda + todo" t)
(autoload 'open-timesheet "my-autoloads/my-defuns" "\
Open my EDF timesheet" t)
(autoload 'crontab-e "my-autoloads/my-defuns" "\
Run `crontab -e' in a emacs buffer." t)
(autoload 'advice-unadvice "my-autoloads/my-defuns" "\
Remove all advices from symbol SYM.

(fn SYM)" t)
(autoload 'mult-by "my-autoloads/my-defuns" "\


(fn BY)")
(autoload 'mult-in-rectangle "my-autoloads/my-defuns" "\
Multiplies all numbers in region by some coefficient.

FIXME: should support non-rectangular regions

FIXME: does not work when the region is not rectangular at the end of
lines, e.g.

2 + 2
2
2
2 

(fn START END)" t)
(autoload 'copy-html-to-ohm "my-autoloads/my-defuns")
(autoload 'my-delete-word "my-autoloads/my-defuns" "\
Delete characters forward until encountering the end of a word.
  With argument, do this that many times.
  This command does not push text to `kill-ring'.

(fn ARG)" t)
(autoload 'my-backward-delete-word "my-autoloads/my-defuns" "\
Delete characters backward until encountering the beginning of a word.
  With argument, do this that many times.
  This command does not push text to `kill-ring'.

(fn ARG)" t)
(autoload 'suspend "my-autoloads/my-defuns" "\
Suspend the system using systemctl syspend" t)
(autoload 'reload-this-buffer "my-autoloads/my-defuns" "\
Kill and re-open the current buffer" t)
(autoload 'fix-evil "my-autoloads/my-defuns" nil t)
(autoload 'arrayify "my-autoloads/my-defuns" "\
Turn selection into a QUOTEd, separated one-liner.

(fn START END QUOTE SEPARATOR)" t)
(autoload 'buffer-mode-histogram "my-autoloads/my-defuns" "\
Display a histogram of Emacs buffer modes." t)
(autoload 'reindent-buffer-with-vim "my-autoloads/my-defuns" "\
Reindent buffer file with vim." t)
(autoload 'sort-code-block "my-autoloads/my-defuns" "\
Alphabetically sorts code blocks in a file, starting with #
start:sort and ending with # end:sort, where # is the comment
char of the language you are editing

(fn COMMENT-CHAR)")
(autoload 'sort-elisp-block "my-autoloads/my-defuns" "\
Alphabetically sort a block of elisp code.

The block should be encased by
;; start:sort
;; end:sort" t)
(autoload 'query-replace-symbol "my-autoloads/my-defuns" "\
Do query-replace current word with" t)
(autoload 'github-package "my-autoloads/my-defuns")
(autoload 'hdl-self-op "my-autoloads/my-defuns" "\


(fn OP)")
(autoload 'hdl-i++ "my-autoloads/my-defuns" "\
Insert a hdl i++ for either the current selection or symbol at point." t)
(autoload 'hdl-i-- "my-autoloads/my-defuns" "\
Insert a hdl i-- for either the current selection or symbol at point." t)
(autoload 'normalize-comment-strings "my-autoloads/my-defuns" nil t)
(defvar current-date-format "%Y-%m-%d" "\
Format of date to insert with `insert-current-time' func.
Note the weekly scope of the command's precision.")
(autoload 'insert-current-date "my-autoloads/my-defuns" "\
insert the current date into the buffer.
The date will follow the format in `current-date-format'" t)
(autoload 'fix-latex-pasted-text "my-autoloads/my-defuns" "\
Fix text pasted from Latex PDFs.

Text copy pasted from Latex likes to hyphen- ate inappropriately.

This function tries to de hyphenate them." t)
(autoload 'calc-popup "my-autoloads/my-defuns" "\
Popup a full frame calc buffer." t)
(defvar my/xdg-data-dirs (progn (require 'xdg) (mapcar (lambda (dir) (expand-file-name "applications" dir)) (cons (xdg-data-home) (xdg-data-dirs)))) "\
Directories in which to search for applications (.desktop files).")
(autoload 'my/list-desktop-files "my-autoloads/my-defuns" "\
Return an alist of all Linux applications.
Each list entry is a pair of (desktop-name . desktop-file).
This function always returns its elements in a stable order.")
(autoload 'my/mime-get-buffer-mime-type "my-autoloads/my-defuns")
(autoload 'my/mime-set-mime-type "my-autoloads/my-defuns" "\


(fn MIME-TYPE HANDLER)")
(autoload 'my/update-mime-type "my-autoloads/my-defuns" "\
Update the mime association of the current file." t)
(autoload 'register-new-mime-type "my-autoloads/my-defuns" "\


(fn HANDLER EXTENSION &optional EXECUTABLE LOGO COMMENT)")
(autoload 'my/register-mime-types "my-autoloads/my-defuns" "\
Register a few mimetypes that are useful for me.

Make sure perl-file-mimeinfo is installed." t)
(autoload 'my/resize-org-latex-overlays "my-autoloads/my-defuns" "\
Helper function for latex text scaling.

From https://www.reddit.com/r/orgmode/comments/165zeuu/delighted_by_org_svg_preview/")
(autoload 'org-archive-done "my-autoloads/my-defuns" "\
Interactive wrapper for org-archive-all-done" t)
(autoload 'org-link-get "my-autoloads/my-defuns" "\
Extract URL from org-mode link and add return it")
(autoload 'org-edit-drawio "my-autoloads/my-defuns" "\
Open Drawio on the image at point." t)
(autoload 'org-edit-inkscape "my-autoloads/my-defuns" "\
Open Inkscape on the image at point." t)
(autoload 'my/edit-image-helper "my-autoloads/my-defuns" "\


(fn HELPER)")
(autoload 'my/edit-gimp "my-autoloads/my-defuns" "\
Open GIMP on the image at point." t)
(autoload 'my/edit-pinta "my-autoloads/my-defuns" "\
Open Pinta on the image at point." t)
(autoload 'my/org-sort-all-org-entries "my-autoloads/my-defuns" "\
" t)
(autoload '+org-sort-entries-recursive "my-autoloads/my-defuns" "\
Call `org-sort-entries' recursively on tree at point.
If KEY, use it; otherwise read key interactively.

(fn &optional KEY)" t)
(autoload '+org-sort-entries-recursive-multi "my-autoloads/my-defuns" "\
Call `+org-sort-entries-recursive'.
If KEYS, call it for each of them; otherwise call interactively
until \\[keyboard-quit] is pressed.

(fn &optional KEYS)" t)
(autoload 'ap/inline-org-inbox-link "my-autoloads/my-defuns" "\
Should probably remove this." t)
(defvar unpackaged/org-export-html-with-useful-ids-mode nil "\
Non-nil if Unpackaged/Org-Export-Html-With-Useful-Ids mode is enabled.
See the `unpackaged/org-export-html-with-useful-ids-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `unpackaged/org-export-html-with-useful-ids-mode'.")
(custom-autoload 'unpackaged/org-export-html-with-useful-ids-mode "my-autoloads/my-defuns" nil)
(autoload 'unpackaged/org-export-html-with-useful-ids-mode "my-autoloads/my-defuns" "\
Attempt to export Org as HTML with useful link IDs.

Instead of random IDs like \"#orga1b2c3\", use heading titles,
made unique when necessary.

This is a global minor mode.  If called interactively, toggle the
`Unpackaged/Org-Export-Html-With-Useful-Ids mode' mode.  If the prefix
argument is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value
\\='unpackaged/org-export-html-with-useful-ids-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'unpackaged/org-export-get-reference "my-autoloads/my-defuns" "\
Like `org-export-get-reference',
except uses heading titles instead of random numbers.

(fn DATUM INFO)")
(autoload 'unpackaged/org-export-new-title-reference "my-autoloads/my-defuns" "\
Return new reference for DATUM that is unique in CACHE.

(fn DATUM CACHE)")
(autoload 'org-get-linked-files "my-autoloads/my-defuns" "\
Get all of the `file' type links in a buffer.
Current buffer is assumed unless specified by BUFFER

(fn &optional BUFFER)")
(autoload 'org-get-links "my-autoloads/my-defuns" "\
Get all of the `file' type links in a buffer.
Current buffer is assumed unless specified by BUFFER

(fn &optional BUFFER)")
(autoload 'org-global-props "my-autoloads/my-defuns" "\
Get the plists of global org properties of current buffer.

(fn &optional PROPERTY BUFFER)")
(autoload 'org-global-prop-value "my-autoloads/my-defuns" "\
Get global org property KEY of current buffer.

(fn KEY)")
(defvar org-default-publish-dest "nfs:/home/public" "\
Default org publishing destination for `org-publish-this-file'.
It will be pushed with rsync.")
(autoload 'org-publish-this-file "my-autoloads/my-defuns" "\
Publish this Org mode file.

If a DEST property is specified in the org file it will by used
as the destination. e.g. the following will set the copy
destination of the file.

#+DEST: ohm:public_html/notes/


Copying is done with rsync, which must be installed on both the
local and remote servers." t)
(autoload 'org-rename-file-at-point "my-autoloads/my-defuns" nil t)
(autoload 'org-move-linked-file "my-autoloads/my-defuns" "\


(fn ROOTPATH OLD NEW)")
(autoload 'org-report-dead-links "my-autoloads/my-defuns" "\
Create a report of dead files in my org mode notes directory." t)
(autoload 'org-table-export-all "my-autoloads/my-defuns" "\
Export to CSV all named tables in current org mode file" t)
(autoload 'org-latex-preview-all "my-autoloads/my-defuns" nil t)
(autoload 'org-latex-preview-clear "my-autoloads/my-defuns" nil t)
(autoload 'scimax/org-return "my-autoloads/my-defuns" "\
Add new list item, heading or table row with RET.
   A double return on an empty element deletes it.
   Use a prefix arg to get regular RET. 

(fn &optional IGNORE)" t)
(autoload 'org-toggle-checkbox-presence "my-autoloads/my-defuns" "\
Toggle the presence of org list checkboxes." t)
(autoload 'org-procrastinate-all "my-autoloads/my-defuns" "\
Carry forward uncompleted tasks.
Updates overdue tasks to be due today." t)
(autoload 'org-procrastinate "my-autoloads/my-defuns" nil t)
(autoload 'org-carry-forward-uncompleted-tasks "my-autoloads/my-defuns" "\
Carry forward uncompleted tasks.

Updates overdue tasks to be due today.

(fn &optional PROCRASTINATE)" t)
(autoload 'ap/org-log-weight "my-autoloads/my-defuns" "\
Log today's weight in my notes file." t)
(autoload '+org-shrink-this-image "my-autoloads/my-defuns" nil t)
(autoload '+org-shrink-and-replace-this-image "my-autoloads/my-defuns" nil t)
(autoload 'pandoc-buffer-to-org "my-autoloads/my-defuns" nil t)
(autoload 'org-shorten-url-by-title "my-autoloads/my-defuns" "\
Use title of URL at point as link name." t)
(autoload 'md-shorten-url-by-title "my-autoloads/my-defuns" nil t)
(autoload 'org-capture-url-from-clipboard "my-autoloads/my-defuns" "\
Capture a URL from clipboard and paste it as an org link

(fn _)" t)
(autoload 'my/url->org "my-autoloads/my-defuns" "\
Convert the URL at point into an Org mode formatted link. The
  title of the page is retrieved from the web page" t)
(autoload 'my/url->md "my-autoloads/my-defuns" "\
Convert the URL at point into an md mode formatted link. The
  title of the page is retrieved from the web page" t)
(autoload 'org-shorten-indico-url "my-autoloads/my-defuns" "\
Takes an indico (or some other url) of the form xxxxx...xxx/some_file.pdf
and shortens it into an org mode link consisting of just `some file`" t)
(autoload 'md-shorten-indico-url "my-autoloads/my-defuns" nil t)
(autoload 'org-link->markdown "my-autoloads/my-defuns" "\
Convert Org mode link at point to markdown." t)
(autoload 'markdown-link->org "my-autoloads/my-defuns" "\
Convert Markdown link at point to Org." t)
(autoload 'org-link-copy "my-autoloads/my-defuns" "\
Extract URL from org-mode link and add it to kill ring.

(fn &optional ARG)" t)
(autoload 'org-remove-link-and-trash-linked-file "my-autoloads/my-defuns" "\
Remove `org-mode' link at point and trash linked file." t)
(autoload 'org-copy-region-as-markdown "my-autoloads/my-defuns" "\
Copy the region (in Org) to the system clipboard as Markdown." t)
(autoload 'org-web-tools--get-url "my-autoloads/my-defuns" "\
Return content for URL as string.
This uses `url-retrieve-synchronously' to make a request with the
URL, then returns the response body.  Since that function returns
the entire response, including headers, we must remove the
headers ourselves.

(fn URL)")
(autoload 'org-web-tools--html-title "my-autoloads/my-defuns" "\
Return title of HTML page, or nil if it has none.
Uses the `dom' library.

(fn HTML)")
(autoload 'www-get-page-title "my-autoloads/my-defuns" "\
Gets the title of a webpage at URL

(fn URL)")
(autoload 'org-capture-url "my-autoloads/my-defuns" "\


(fn URL)")
(autoload 'org-link-parse "my-autoloads/my-defuns" "\


(fn LINK)")
(autoload 'consult-recent-file "my-autoloads/my-defuns" "\
Find recent using `completing-read'.

This version is modified to sort by recent files" t)
(autoload 'consult-project-find-file "my-autoloads/my-defuns" "\
Find project files using `completing-read'." t)
(register-definition-prefixes "my-autoloads/my-defuns" '("consult--recent-files-sort" "gvim" "normalize-comment-strings-length" "org-drawio-template"))


;;; Generated autoloads from my-autoloads/my-tex.el

(autoload 'texify-quotation-marks "my-autoloads/my-tex" nil t)
(autoload 'tex-follow-link-at-point "my-autoloads/my-tex" nil t)
(defvar default-tex-master nil)
(autoload 'my/set-default-tex-master "my-autoloads/my-tex" "\
Set the master tex file for the current project." t)
(autoload 'TeX-toggle-folding "my-autoloads/my-tex" nil t)
(autoload 'tex-link-insert "my-autoloads/my-tex" "\
Insert TeX href link" t)
(autoload 'reftex-toc-set-max-level "my-autoloads/my-tex" nil t)
(defvar line-fill-paragraph-non-separators (append (list "n.b." "i.e." "e.g." "c.f." "viz." "eg." "ie.") (mapcar (lambda (x) (concat (upcase (char-to-string x)) ".")) (number-sequence 97 122))))
(autoload 'ap/line-fill-paragraph "my-autoloads/my-tex" "\
When called with prefix argument call `fill-paragraph'.
   Otherwise split the current paragraph into one sentence per line.

(fn &optional P)" t)
(autoload 'tex-expand-and-insert "my-autoloads/my-tex" "\


(fn MACRO)" t)
(autoload 'tex-underline "my-autoloads/my-tex" "\
Make the current TeX selection bold." t)
(autoload 'tex-bold "my-autoloads/my-tex" "\
Make the current TeX selection bold." t)
(autoload 'tex-italic "my-autoloads/my-tex" "\
Make the current TeX selection italic." t)
(autoload 'tex-tt "my-autoloads/my-tex" "\
Make the current TeX selection typewriter." t)
(autoload 'tex-glossarify "my-autoloads/my-tex" "\
Make the current TeX selection a glossary entry." t)
(autoload 'tex-Glossarify "my-autoloads/my-tex" "\
Make the current TeX selection a Glossary entry." t)
(autoload 'hook/modify-latex-hyphen-syntax "my-autoloads/my-tex" "\
Treat hyphenated words as one.")
(autoload 'electric-space "my-autoloads/my-tex" "\
Trying to get Emacs to do semantic linefeeds." t)
(autoload 'toggle-electric-space "my-autoloads/my-tex" nil t)
(register-definition-prefixes "my-autoloads/my-tex" '("electric-space-on-p"))


;;; Generated autoloads from my-autoloads/popup-acronyms.el

(register-definition-prefixes "my-autoloads/popup-acronyms" '("acronym-alist" "expand-acronym"))


;;; Generated autoloads from my-autoloads/regulator.el

(autoload 'find-regulator-divider "my-autoloads/regulator" "\
Find resistors for a voltage regulator." t)
(register-definition-prefixes "my-autoloads/regulator" '("e192" "e24" "e48" "e96" "regulator-format-resistor"))


;;; Generated autoloads from my-autoloads/timesheet.el

(autoload 'ymd-to-weekday "my-autoloads/timesheet" "\


(fn C Y M D)")
(autoload 'weekday-to-abbr "my-autoloads/timesheet" "\


(fn D)")
(autoload 'month-to-number "my-autoloads/timesheet" "\


(fn M)")
(autoload 'get-day-of-week "my-autoloads/timesheet" "\


(fn TITLE DAY)")
(autoload 'clock-to-float "my-autoloads/timesheet" "\
Convert a clock time (e.g. 12:30) to a float (e.g. 12.5)

(fn TIME)")
(autoload 'range-to-time "my-autoloads/timesheet" "\
Convert a 12hr clock time range time (e.g. 1-2:30)
to a float amount of time (1.5)

(fn RANGE)")
(autoload 'update-all-histograms "my-autoloads/timesheet")
(autoload 'update-all-src-blocks "my-autoloads/timesheet")
(autoload 'bin-data "my-autoloads/timesheet" "\


(fn DATA &key NORMALIZE SORT)")
(autoload 'plot-chart "my-autoloads/timesheet" "\
Simple function to plot an ascii bar chart.

It accepts DATA in the form of an alist of the form
='((KEY . VAL) (KEY . VAL) (KEY . VAL)) and will
produce a bar chart where for each key val is summed.

NORMALIZE will normalize the bar chart to some number of ASCII symbols.

SORT to non-nill will sort the list. 

(fn DATA KEYWORD VALWORD &key NORMALIZE SORT UPLOT TITLE)")
(autoload 'filter-work-chart "my-autoloads/timesheet" "\


(fn DATA)")
(autoload 'week-number "my-autoloads/timesheet" "\


(fn MONTH DAY YEAR)")
(autoload 'iso-week-to-time "my-autoloads/timesheet" "\


(fn YEAR WEEK DAY)")
(autoload 'plot-weekly-work-goals "my-autoloads/timesheet" "\


(fn DATA)")
(autoload 'plot-weekly-work-goals-for-date-range "my-autoloads/timesheet" "\


(fn START-YEAR START-MONTH END-YEAR END-MONTH)")
(autoload 'plot-monthly-work-chart "my-autoloads/timesheet" "\


(fn DATA &key UPLOT TITLE)")
(autoload 'date-range-to-year-month-list "my-autoloads/timesheet" "\


(fn START-YEAR START-MONTH END-YEAR END-MONTH)")
(autoload 'add-yyyy-mm-to-table "my-autoloads/timesheet" "\


(fn DATA YEAR MONTH)")
(autoload 'get-work-data-in-date-range "my-autoloads/timesheet" "\


(fn TITLE &key START-YEAR START-MONTH END-YEAR END-MONTH SHORT MEETINGS MEETINGS-DETAILED HLINES PROJECTS)")
(autoload 'plot-work-chart-in-date-range "my-autoloads/timesheet" "\


(fn TITLE &key START-YEAR START-MONTH END-YEAR END-MONTH SHORT MEETINGS MEETINGS-DETAILED)")
(autoload 'plot-weekly-summary-for-month "my-autoloads/timesheet" "\


(fn YEAR MONTH)")
(autoload 'filter-timesheet-for-hours "my-autoloads/timesheet" "\


(fn DATA)")
(autoload 'plot-monthly-histogram "my-autoloads/timesheet" "\


(fn TITLE DATA)")
(autoload 'org-insert-monthly-timesheet "my-autoloads/timesheet" "\
Insert a new timesheet for the current month" t)

;;; End of scraped data

(provide 'loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loaddefs.el ends here
