;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el


;; Local Variables:
;; eval: (make-variable-buffer-local 'after-save-hook)
;; https://www.emacswiki.org/emacs/UntabifyUponSave
;; eval: (add-hook 'write-contents-hooks 'sort-elisp-block nil t)
;; End:

;; start:sort
(package! all-the-icons)
(package! all-the-icons-dired)
(package! all-the-icons-ibuffer)
(package! all-the-icons-ivy)
(package! base16-theme)
(package! browse-at-remote)
(package! company-jedi)
(package! counsel-etags)
(package! crontab-mode)
(package! doom-todo-ivy :recipe (:host github :repo "jsmestad/doom-todo-ivy"))
(package! dumb-jump)
(package! eaf :recipe (:host github :repo "manateelazycat/emacs-application-framework"))
(package! emojify)
(package! etags-table)
(package! evil-leader)
(package! flycheck-clang-tidy)
(package! flymake-json)
(package! graphviz-dot-mode)
(package! hl-line :disable t)
(package! htmlize :recipe (:host github :repo "hniksic/emacs-htmlize"))
(package! irony)
(package! logview)
(package! lorem-ipsum)
(package! lsp-mode :recipe (:host github :repo "emacs-lsp/lsp-mode"))
(package! lsp-pyright)
(package! magit-todos)
(package! mixed-pitch)
(package! org-attach-screenshot)
(package! org-download :recipe (:host github :repo "abo-abo/org-download"))
(package! org-roam :recipe (:host github :repo "org-roam/org-roam"))
(package! ox-clip :recipe (:host github :repo "jkitchin/ox-clip"))
(package! ox-gfm)
(package! pcre2el)
(package! pdf-tools)
(package! scad-mode)
(package! screenshot :recipe (:host github :repo "tecosaur/screenshot"))
(package! toc-org)
(package! vimrc-mode)
(package! visual-fill-column)
(package! vivado-mode :recipe (:host github :repo "ashtonchase/vivado_mode"))
(package! yaml-mode)
;; end:sort

;; start:sort
;;(package! auctex)
;;(package! clang-format)
;;(package! clang-format+)
;;(package! company)
;;(package! company-box)
;;(package! company-tabnine)
;;(package! elfeed)
;;(package! elpy)
;;(package! esup)
;;(package! fira-code-mode)
;;(package! fzf :recipe (:host github :repo "seenaburns/fzf.el"))
;;(package! good-scroll :recipe (:host github :repo "io12/good-scroll.el"))
;;(package! leuven-theme)
;;(package! org-bullets)
;;(package! org-gcal :recipe (:host github :repo "kidd/org-gcal.el"))
;;(package! org-roam-server)
;;(package! org-sync)
;;(package! org-table-comment)
;;(package! rainbow-mode) ;; included in rgb package
;;(package! theme-changer :recipe (:host github :repo "hadronzoo/theme-changer"))
;;(package! vterm)
;; end:sort
