(deftheme leuven
  "Created 2020-03-26.")

(custom-theme-set-variables
 'leuven
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["black" "red3" "ForestGreen" "yellow3" "blue" "magenta3" "DeepSkyBlue" "gray50"]))

(custom-theme-set-faces
 'leuven
 '(bold ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(bold-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "black"))))
 '(italic ((((class color) (min-colors 89)) (:slant italic :foreground "#1A1A1A"))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#21BDFF"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#FFFFFF" :background "#333333"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#4C9ED9" :background "white"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#E6ECFF" :extend t))))
 '(region ((((class color) (min-colors 89)) (:background "#8ED3FF" :extend t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:weight bold :background "#FFFF00"))))
 '(isearch ((((class color) (min-colors 89)) (:underline "black" :foreground "white" :background "#5974AB"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FFCCCC"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFF00"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "#FFFFAB"))))
 '(query-replace ((((class color) (min-colors 89)) (:inherit isearch))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:foreground "#D2D2D2"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "white"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:foreground "#CC0000" :background "#FFFF88"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "white"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "#FFFFAB"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#1A2F54") :foreground "#85CEEB" :background "#335EA8"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#4E4E4C") :foreground "#F0F0EF" :background "#9B9C97"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "yellow"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "gold"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#008ED1"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(success ((((class color) (min-colors 89)) (:foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#006FE0"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#8D8D84"))))
 '(font-lock-comment-face ((t (:foreground "#8D8D84" :slant normal))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#036A07"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#006699"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#0000FF"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:weight normal :foreground "#6434A3"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#BA36A5"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#E5786D"))))
 '(button ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(header-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "black") :foreground "black" :background "#F0F0F0"))))
 '(message-header-name ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#A3A3A2"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#006DAF"))))
 '(message-header-other ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "black"))))
 '(message-header-to ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#006DAF"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#5050B0" :background "#F6F6F6"))))
 '(message-separator ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#BDC2C6"))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#3399CC"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "forest green"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#0000FF" :background "#DDDDFF"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#888888"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#CC99CC"))))
 '(diff-header ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#990099" :background "#FFEEFF"))))
 '(diff-index ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#3A993A" :background "#CDFFD8"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:background "#DBEDFF"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#CC3333" :background "#FFDCE0"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:background "#97F295"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#FFB6BA"))))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#FEE8E9"))))
 '(smerge-upper ((((class color) (min-colors 89)) (:foreground "#0000FF" :background "#DDDDFF"))))
 '(smerge-lower ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#FEE8E9"))))
 '(smerge-markers ((((class color) (min-colors 89)) (:background "#FFE5CC"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#AAAAFF"))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline (:style wave :color "#F4EB80") :background "#FAF7CC" :inherit nil))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline (:style wave :color "#FAA7A5") :background "#F4D7DA" :inherit nil))))
 '(anzu-match-1 ((((class color) (min-colors 89)) (:foreground "black" :background "aquamarine"))))
 '(anzu-match-2 ((((class color) (min-colors 89)) (:foreground "black" :background "springgreen"))))
 '(anzu-match-3 ((((class color) (min-colors 89)) (:foreground "black" :background "red"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "black" :background "#80FF80"))))
 '(anzu-mode-line-no-match ((((class color) (min-colors 89)) (:foreground "black" :background "#FF8080"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit query-replace))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:weight bold :foreground "#BD33FD" :background "#FDBD33"))))
 '(calendar-month-header ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(calendar-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(calendar-weekday-header ((((class color) (min-colors 89)) (:weight bold :foreground "#1662AF"))))
 '(calendar-weekend-header ((((class color) (min-colors 89)) (:weight bold :foreground "#4E4E4E"))))
 '(change-log-date ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(change-log-file ((((class color) (min-colors 89)) (:weight bold :foreground "#4183C4"))))
 '(change-log-list ((((class color) (min-colors 89)) (:foreground "black" :background "#75EEC7"))))
 '(change-log-name ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(comint-highlight-input ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#EBF4FE"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#D1DAE4"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :foreground "#F9ECCC" :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "#0052A4"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :foreground "#F9ECCC"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :foreground "#B000B0" :inherit company-tooltip))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#EBF4FE"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#2415FF"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:weight normal :foreground "#C0C0C0" :inherit hl-line))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#EBF4FE"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#D1DAE4"))))
 '(compilation-error ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight bold :foreground "#2A489E"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:weight bold :foreground "#A535AE"))))
 '(compilation-warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:weight bold :foreground "green"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:weight bold :foreground "violet"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "lightgrey"))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "grey90"))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:box (:line-width 2 :style pressed-button) :foreground "black" :background "light grey"))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:underline t))))
 '(custom-changed ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-comment ((((class color) (min-colors 89)) (:background "gray85"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(custom-documentation ((((class color) (min-colors 89)) (nil))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:height 1.2 :weight bold :foreground "blue1"))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "red1"))))
 '(custom-invalid ((((class color) (min-colors 89)) (:foreground "yellow" :background "red"))))
 '(custom-link ((((class color) (min-colors 89)) (:underline t :foreground "blue1"))))
 '(custom-modified ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-rogue ((((class color) (min-colors 89)) (:foreground "pink" :background "black"))))
 '(custom-saved ((((class color) (min-colors 89)) (:underline t))))
 '(custom-set ((((class color) (min-colors 89)) (:foreground "blue" :background "white"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(custom-themed ((((class color) (min-colors 89)) (:foreground "white" :background "blue1"))))
 '(custom-variable-button ((((class color) (min-colors 89)) (:weight bold :underline t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "blue1"))))
 '(custom-visibility ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "blue3" :background "#DBEDFF"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "red3" :background "#FFDCE0"))))
 '(diff-hl-dired-change ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FFA335"))))
 '(diff-hl-dired-delete ((((class color) (min-colors 89)) (:weight bold :foreground "#D73915"))))
 '(diff-hl-dired-ignored ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "#C0BBAB"))))
 '(diff-hl-dired-insert ((((class color) (min-colors 89)) (:weight bold :foreground "#B9B9BA"))))
 '(diff-hl-dired-unknown ((((class color) (min-colors 89)) (:foreground "white" :background "#3F3BB4"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "green4" :background "#CDFFD8"))))
 '(dired-directory ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dired-header ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:strike-through t :foreground "red"))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#1F8DD6"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:weight bold :foreground "red" :background "#FFE4FF"))))
 '(file-name-shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:color "#FE251E" :style wave) :weight bold :background "#FFE1E1"))))
 '(flycheck-error-list-line-number ((((class color) (min-colors 89)) (:foreground "#A535AE"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#FE251E"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#158A15"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#F4A939"))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:color "#158A15" :style wave) :weight bold))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:color "#F4A939" :style wave) :weight bold :background "#FFFFBE"))))
 '(info-header-node ((((class color) (min-colors 89)) (:underline t :foreground "orange"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:underline t :foreground "dodger blue"))))
 '(info-index-match ((((class color) (min-colors 89)) (:weight bold :foreground nil :background "#FDBD33"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB" :extend t))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "black"))))
 '(info-node ((((class color) (min-colors 89)) (:underline t :foreground "blue"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0" :extend t))))
 '(info-xref ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "red" :background "#E6E6E6"))))
 '(magit-blame-hash ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "red" :background "#E6E6E6"))))
 '(magit-blame-name ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "#036A07" :background "#E6E6E6"))))
 '(magit-blame-date ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "blue" :background "#E6E6E6"))))
 '(magit-blame-summary ((((class color) (min-colors 89)) (:overline "#A7A7A7" :weight bold :foreground "#707070" :background "#E6E6E6"))))
 '(match ((((class color) (min-colors 89)) (:weight bold :background "#FFFF00"))))
 '(next-error ((((class color) (min-colors 89)) (:height 1.1 :underline nil :foreground "white" :background "#9E3699"))))
 '(nobreak-space ((((class color) (min-colors 89)) (:background "#CCE8F6"))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:weight bold :foreground "#3774CC" :background "#E4EBFE"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#327ACD" :background "#F3F7FC"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "black" :background "#EEC900"))))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-agenda-current-time ((((class color) (min-colors 89)) (:underline t :foreground "#1662AF"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#1662AF"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#4E4E4E"))))
 '(org-agenda-diary ((((class color) (min-colors 89)) (:weight bold :foreground "green4" :background "light blue"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "gold2"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#555555"))))
 '(org-agenda-filter-category ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-filter-effort ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-filter-regexp ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-filter-tags ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#E77D63"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#1F8DD6"))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "gray70"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#000088" :background "#FFFFE0" :extend t))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:underline "#A7A6AA" :foreground "#555555" :background "#E2E1D5" :extend t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:overline "#A7A6AA" :foreground "#555555" :background "#E2E1D5" :extend t))))
 '(org-checkbox ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :style pressed-button) :foreground "#123555" :background "#A3A3A3"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "white" :background "SkyBlue4"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#006400" :background "#FDFFF7" :extend t))))
 '(org-column ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-column-title ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#00459E"))))
 '(org-default ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF"))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#484848"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#008ED1" :background "#EAEAFF"))))
 '(org-document-title ((((class color) (min-colors 89)) (:height 1.8 :weight bold :foreground "black"))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#BBBBBB") :foreground "#BBBBBB" :background "#F0F0F0"))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "light sky blue"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:underline nil :foreground "#999999"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#008ED1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "chocolate1"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:height 1.0 :weight normal :strike-through t :foreground "#ADADAD"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#E2E2E2"))))
 '(org-latex-and-related ((((class color) (min-colors 89)) (:foreground "#336699" :background "white"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0" :extend t))))
 '(org-level-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB" :extend t))))
 '(org-level-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF" :extend t))))
 '(org-level-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300" :extend t))))
 '(org-level-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D" :extend t))))
 '(org-level-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC" :extend t))))
 '(org-level-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#2EAE2C" :extend t))))
 '(org-level-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#FD8008" :extend t))))
 '(org-link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(org-list-dt ((((class color) (min-colors 89)) (:weight bold :foreground "#335EA8"))))
 '(org-macro ((((class color) (min-colors 89)) (:weight bold :foreground "#EDB802"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:slant normal :foreground "#008ED1" :background "#EAEAFF"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#335EA8") :foreground "black" :background "#FFA335"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#335EA8") :foreground "white" :background "#FF4040"))))
 '(org-property-value ((((class color) (min-colors 89)) (:foreground "#00A000"))))
 '(org-quote ((((class color) (min-colors 89)) (:slant italic :foreground "dim gray" :background "#FFFFE0"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#333333"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#1466C6"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#3774CC"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:weight bold :foreground "#00BB00" :background "#EAFFEA"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "dark green" :background "#EAFFEA"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight normal :slant italic :foreground "#9A9FA4" :background "white"))))
 '(org-target ((((class color) (min-colors 89)) (:foreground "#FF6DAF"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#CFCFCF"))))
 '(org-todo ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#D8ABA7") :foreground "#D8ABA7" :background "#FFE6E4"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#FF5555"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#0066CC" :background "#F7FDFF"))))
 '(org-verse ((((class color) (min-colors 89)) (:slant italic :foreground "dim gray" :background "#EEEEEE"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#CCE7FF"))))
 '(outline-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0" :extend t))))
 '(outline-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB" :extend t))))
 '(outline-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF" :extend t))))
 '(outline-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300" :extend t))))
 '(outline-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D" :extend t))))
 '(outline-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC" :extend t))))
 '(outline-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#2EAE2C" :extend t))))
 '(outline-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#FD8008" :extend t))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#707183"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#7388D6"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#909183"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#709870"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#907373"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#6276BA"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#858580"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#80A880"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#887070"))))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#C0E8C3"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(tool-bar ((((class color) (min-colors 89)) (:box (:line-width 1 :style released-button) :foreground "black" :background "gray75"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "black" :background "light yellow"))))
 '(which-func ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "white"))))
 '(which-key-local-map-description-face ((((class color) (min-colors 89)) (:weight bold :background "#F3F7FC" :inherit which-key-command-description-face))))
 '(widget-button ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "dim gray"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(yas-field-highlight-face ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#838383") :foreground "black" :background "#D4DCD8"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF")))))

(provide-theme 'leuven)
