(deftheme solarized-light-white
  "Created 2020-03-03.")

(custom-theme-set-variables
 'solarized-light-white
 '(ansi-color-names-vector ["#ffffff" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#839496"])
 '(compilation-message-face (quote default))
 '(cua-normal-cursor-color "#657b83")
 '(cua-read-only-cursor-color "#859900")
 '(cua-global-mark-cursor-color "#2aa198")
 '(cua-overwrite-cursor-color "#b58900"))

(custom-theme-set-faces
 'solarized-light-white
 '(button ((t (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#657b83" :inverse-video t))))
 '(error ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#ffffff"))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline nil :underline "#ffffff" :foreground "#657b83" :background "#ffffff" :box (:line-width 2 :color "#ffffff" :style unspecified)))))
 '(highlight ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#b58900" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t :weight normal))))
 '(match ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#586e75" :weight bold))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#657b83" :background "#ffffff"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(mode-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#ffffff" :underline "#cccec4" :foreground "#657b83" :background "#ffffff" :box (:line-width 1 :color "#ffffff" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#ffffff" :underline "#cccec4" :foreground "#93a1a1" :background "#ffffff" :box (:line-width 1 :color "#ffffff" :style unspecified)))))
 '(region ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#586e75"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#cccec4"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#2aa198" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#93a1a1" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#859900" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground unspecified :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#dc322f" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight bold))))
 '(completions-annotations ((t (:foreground "#93a1a1"))))
 '(cua-global-mark ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#ffffff"))))
 '(cua-rectangle ((((class color) (min-colors 89)) (:inherit region :background "#d33682" :foreground "#ffffff"))))
 '(cua-rectangle-noselect ((((class color) (min-colors 89)) (:inherit region :background "#ffffff" :foreground "#93a1a1"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#268bd2"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#657b83" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :underline t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#d33682" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#ffffff" :bold t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#657b83" :weight bold :slant normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant normal))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#2aa198" :slant normal))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:inherit error :weight bold))))
 '(all-the-icons-red ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(all-the-icons-lred ((((class color) (min-colors 89)) (:foreground "#ff6849"))))
 '(all-the-icons-dred ((((class color) (min-colors 89)) (:foreground "#a7020a"))))
 '(all-the-icons-red-alt ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(all-the-icons-green ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(all-the-icons-lgreen ((((class color) (min-colors 89)) (:foreground "#b3c34d"))))
 '(all-the-icons-dgreen ((((class color) (min-colors 89)) (:foreground "#5b7300"))))
 '(all-the-icons-yellow ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(all-the-icons-lyellow ((((class color) (min-colors 89)) (:foreground "#e1af4b"))))
 '(all-the-icons-dyellow ((((class color) (min-colors 89)) (:foreground "#866300"))))
 '(all-the-icons-blue ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(all-the-icons-blue-alt ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(all-the-icons-lblue ((((class color) (min-colors 89)) (:foreground "#74adf5"))))
 '(all-the-icons-dblue ((((class color) (min-colors 89)) (:foreground "#0061a8"))))
 '(all-the-icons-maroon ((((class color) (min-colors 89)) (:foreground "#a00559"))))
 '(all-the-icons-lmaroon ((((class color) (min-colors 89)) (:foreground "#a00559"))))
 '(all-the-icons-dmaroon ((((class color) (min-colors 89)) (:foreground "#a00559"))))
 '(all-the-icons-purple ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(all-the-icons-lpurple ((((class color) (min-colors 89)) (:foreground "#8d85e7"))))
 '(all-the-icons-dpurple ((((class color) (min-colors 89)) (:foreground "#243e9b"))))
 '(all-the-icons-orange ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(all-the-icons-lorange ((((class color) (min-colors 89)) (:foreground "#fb7640"))))
 '(all-the-icons-dorange ((((class color) (min-colors 89)) (:foreground "#992700"))))
 '(all-the-icons-cyan ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(all-the-icons-cyan-alt ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(all-the-icons-lcyan ((((class color) (min-colors 89)) (:foreground "#6ccec0"))))
 '(all-the-icons-dcyan ((((class color) (min-colors 89)) (:foreground "#007d76"))))
 '(all-the-icons-pink ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(all-the-icons-lpink ((((class color) (min-colors 89)) (:foreground "#ff699e"))))
 '(all-the-icons-dpink ((((class color) (min-colors 89)) (:foreground "#a00559"))))
 '(all-the-icons-silver ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(all-the-icons-lsilver ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(all-the-icons-dsilver ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:inherit isearch))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:inherit isearch :background "#6c71c4"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:inherit isearch :background "#cb4b16"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:inherit isearch :background "#2aa198"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(company-echo ((((class color) (min-colors 89)) nil)))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#dc322f"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#586e75"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#2aa198"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#657b83"))))
 '(company-template-field ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#ffffff"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#ffffff"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight bold))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#bedfcf" :foreground "#247374"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(company-tooltip-search-selection ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#6c71c4" :weight normal))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f" :height 1.2))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#586e75" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#93a1a1" :foreground "#ffffff" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#93a1a1" :foreground "#586e75" :box (:line-width 2 :style pressed-button)))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:inherit underline))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:inherit custom-button-unraised :foreground "#d33682"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#efeac7" :foreground "#657827"))))
 '(diff-changed ((t nil)))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#ffdec8" :foreground "#a33c35"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:background "#dbdb9c" :foreground "#5b6e35"))))
 '(diff-refine-changed ((((class color) (min-colors 89)) (:background "#c3d5e9" :foreground "#246792"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#ffb9a1" :foreground "#8e433d"))))
 '(diff-header ((t (:background "#ffffff"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#657b83" :weight bold))))
 '(diff-context ((((class color) (min-colors 89)) :foreground "#657b83")))
 '(diff-indicator-added ((t (:foreground "#859900"))))
 '(diff-indicator-changed ((t (:foreground "#268bd2"))))
 '(diff-indicator-removed ((t (:foreground "#dc322f"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:background "#e7e8e4" :foreground "#1e6fa2"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:background "#ffdec8" :foreground "#a33c35"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:background "#efeac7" :foreground "#657827"))))
 '(diff-hl-reverted-hunk-highlight ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#876d26"))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#876d26"))))
 '(smerge-lower ((((class color) (min-colors 89)) (:background "#efeac7" :foreground "#657827"))))
 '(smerge-markers ((t (:background "#ffffff"))))
 '(smerge-refined-added ((((class color) (min-colors 89)) (:background "#dbdb9c" :foreground "#5b6e35"))))
 '(smerge-refined-removed ((((class color) (min-colors 89)) (:background "#ffb9a1" :foreground "#8e433d"))))
 '(smerge-upper ((((class color) (min-colors 89)) (:background "#ffdec8" :foreground "#a33c35"))))
 '(epa-mark ((((class color) (min-colors 89)) (:foreground "#d33682" :weight bold))))
 '(epa-string ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(epa-validity-disabled ((((class color) (min-colors 89)) (:inverse-video t :slant italic))))
 '(epa-validity-high ((((class color) (min-colors 89)) (:weight bold))))
 '(epa-validity-low ((((class color) (min-colors 89)) (:slant italic))))
 '(epa-validity-medium ((((class color) (min-colors 89)) (:slant italic))))
 '(eros-result-overlay-face ((t (:background unspecified))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal :underline nil))))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#a7020a" :background "#ff6849" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#866300" :background "#e1af4b" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#268bd2") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#0061a8" :background "#74adf5" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#a7020a" :background "#ff6849" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#866300" :background "#e1af4b" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#0061a8" :background "#74adf5" :weight bold))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#b58900") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#b58900" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc322f") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold :underline t))))
 '(git-commit-comment-action ((((class color) (min-colors 89)) (:foreground "#657b83" :weight bold))))
 '(git-commit-comment-branch-local ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(git-commit-comment-branch-remote ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(git-commit-comment-heading ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:weight normal :foreground "#859900" :background "#ffffff"))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:weight normal :foreground "#dc322f" :background "#ffffff"))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:weight normal :foreground "#268bd2" :background "#ffffff"))))
 '(git-gutter:unchanged ((((class color) (min-colors 89)) (:weight normal :foreground "#93a1a1" :background "#ffffff"))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#dc322f" :weight bold))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight bold))))
 '(highlight-numbers-number ((((class color) (min-colors 89)) (:foreground "#6c71c4" :bold nil))))
 '(info-title-1 ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-title-4 ((((class color) (min-colors 89)) (:weight bold))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic :weight bold))))
 '(info-header-node ((((class color) (min-colors 89)) (:inherit info-node))))
 '(info-header-xref ((((class color) (min-colors 89)) (:inherit info-xref))))
 '(info-index-match ((((class color) (min-colors 89)) (:inherit match))))
 '(info-menu-header ((((class color) (min-colors 89)) (:inherit variable-pitch :weight bold))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(info-xref ((((class color) (min-colors 89)) (:inherit link))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:inherit (link-visited info-xref)))))
 '(ivy-confirm-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:weight bold :background "#ffffff" :underline t))))
 '(ivy-match-required-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(linum ((((class color) (min-colors 89)) (:weight thin :underline nil :foreground "#93a1a1" :background "#ffffff"))))
 '(line-number ((((class color) (min-colors 89)) (:weight thin :underline nil :foreground "#93a1a1" :background "#ffffff"))))
 '(magit-section-highlight ((t (:background "#ffffff"))))
 '(magit-section-heading ((t (:foreground "#b58900" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#cb4b16" :weight bold))))
 '(magit-diff-file-heading ((t (:weight bold))))
 '(magit-diff-file-heading-highlight ((t (:background "#ffffff"))))
 '(magit-diff-file-heading-selection ((t (:background "#ffffff" :foreground "#cb4b16"))))
 '(magit-diff-hunk-heading ((t (:background "#ffffff" :foreground "#876d26"))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#f1d49b" :foreground "#766634"))))
 '(magit-diff-hunk-heading-selection ((t (:background "#ffffff" :foreground "#cb4b16" :weight bold))))
 '(magit-diff-lines-heading ((t (:background "#cb4b16" :foreground "#002b36"))))
 '(magit-diff-context-highlight ((t (:background "#ffffff" :foreground "#586e75"))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:background "#efeac7" :foreground "#657827"))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:background "#efeac7" :foreground "#657827"))))
 '(magit-diff-base ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#876d26"))))
 '(magit-diff-base-highlight ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#876d26"))))
 '(magit-diff-conflict-heading ((((class color) (min-colors 89)) (:inherit magit-diff-hunk-heading))))
 '(magit-diff-context ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:background "#ffdec8" :foreground "#a33c35"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:background "#ffdec8" :foreground "#a33c35"))))
 '(magit-diffstat-added ((t (:foreground "#859900"))))
 '(magit-diffstat-removed ((t (:foreground "#dc322f"))))
 '(magit-process-ok ((t (:foreground "#859900" :weight bold))))
 '(magit-process-ng ((t (:foreground "#dc322f" :weight bold))))
 '(magit-log-author ((t (:foreground "#93a1a1" :weight bold))))
 '(magit-log-date ((t (:foreground "#93a1a1"))))
 '(magit-log-graph ((t (:foreground "#586e75"))))
 '(magit-sequence-pick ((t (:foreground "#866300"))))
 '(magit-sequence-stop ((t (:foreground "#859900"))))
 '(magit-sequence-part ((t (:foreground "#b58900"))))
 '(magit-sequence-head ((t (:foreground "#268bd2"))))
 '(magit-sequence-drop ((t (:foreground "#dc322f"))))
 '(magit-sequence-done ((t (:foreground "#93a1a1"))))
 '(magit-sequence-onto ((t (:foreground "#93a1a1"))))
 '(magit-bisect-good ((t (:foreground "#859900"))))
 '(magit-bisect-skip ((t (:foreground "#b58900"))))
 '(magit-bisect-bad ((t (:foreground "#dc322f"))))
 '(magit-blame-highlight ((t (:background "#ffffff"))))
 '(magit-blame-heading ((t (:background "#ffffff" :box (:color "#ffffff" :line-width 2)))))
 '(magit-blame-summary ((t (:foreground "#657b83"))))
 '(magit-blame-hash ((t (:foreground "#6c71c4"))))
 '(magit-blame-name ((t (:foreground "#6c71c4"))))
 '(magit-blame-date ((t (:foreground "#6c71c4"))))
 '(magit-dimmed ((t (:foreground "#93a1a1"))))
 '(magit-hash ((t (:foreground "#93a1a1"))))
 '(magit-tag ((t (:foreground "#2aa198" :weight bold))))
 '(magit-branch-remote ((t (:foreground "#859900" :weight bold))))
 '(magit-branch-local ((t (:foreground "#268bd2" :weight bold))))
 '(magit-branch-current ((t (:foreground "#268bd2" :weight bold :box t))))
 '(magit-head ((t (:foreground "#268bd2" :weight bold))))
 '(magit-refname ((t (:background "#ffffff" :foreground "#93a1a1" :weight bold))))
 '(magit-refname-stash ((t (:background "#ffffff" :foreground "#93a1a1" :weight bold))))
 '(magit-refname-wip ((t (:background "#ffffff" :foreground "#93a1a1" :weight bold))))
 '(magit-signature-good ((t (:foreground "#859900"))))
 '(magit-signature-bad ((t (:foreground "#dc322f"))))
 '(magit-signature-untrusted ((t (:foreground "#b58900"))))
 '(magit-cherry-unmatched ((t (:foreground "#2aa198"))))
 '(magit-cherry-equivalent ((t (:foreground "#d33682"))))
 '(magit-reflog-commit ((t (:foreground "#859900"))))
 '(magit-reflog-amend ((t (:foreground "#d33682"))))
 '(magit-reflog-merge ((t (:foreground "#859900"))))
 '(magit-reflog-checkout ((t (:foreground "#268bd2"))))
 '(magit-reflog-reset ((t (:foreground "#dc322f"))))
 '(magit-reflog-rebase ((t (:foreground "#d33682"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#859900"))))
 '(magit-reflog-remote ((t (:foreground "#2aa198"))))
 '(magit-reflog-other ((t (:foreground "#2aa198"))))
 '(magit-popup-heading ((t (:foreground "#b58900" :weight bold))))
 '(magit-popup-key ((t (:foreground "#586e75" :weight bold))))
 '(magit-popup-argument ((t (:foreground "#2aa198" :weight bold))))
 '(magit-popup-disabled-argument ((t (:foreground "#93a1a1" :weight normal))))
 '(magit-popup-option-value ((t (:foreground "#2aa198" :weight bold))))
 '(markdown-blockquote-face ((((class color) (min-colors 89)) (:inherit font-lock-doc-face))))
 '(markdown-bold-face ((((class color) (min-colors 89)) (:inherit bold))))
 '(markdown-code-face ((((class color) (min-colors 89)) (:inherit fixed-pitch :foreground "#93a1a1" :background unspecified))))
 '(markdown-comment-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :strike-through t))))
 '(markdown-footnote-marker-face ((((class color) (min-colors 89)) (:inherit default))))
 '(markdown-header-delimiter-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(markdown-header-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-rule-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(markdown-italic-face ((((class color) (min-colors 89)) (:inherit italic))))
 '(markdown-language-keyword-face ((((class color) (min-colors 89)) (:inherit default))))
 '(markdown-line-break-face ((((class color) (min-colors 89)) (:inherit default :underline t))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:inherit default :foreground "#b58900"))))
 '(markdown-link-title-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(markdown-list-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(markdown-math-face ((((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(markdown-metadata-key-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(markdown-metadata-value-face ((((class color) (min-colors 89)) (:inherit default))))
 '(markdown-missing-link-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(markdown-pre-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(markdown-reference-face ((((class color) (min-colors 89)) (:inherit default :foreground "#93a1a1"))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#657b83" :weight normal))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#657b83" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#657b83" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant italic))))
 '(nav-flash-face ((((background light) (class color) (min-colors 89)) (:foreground "#709b732064af" :background "#f1ffdf16b949")) (((background dark) (class color) (min-colors 89)) (:foreground "#55f07313786c" :background "#c5aedc8ecbeb"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#ffffff" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#ffffff")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#657b83" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#ffffff" :weight normal :box (:line-width 2 :color "#ffffff") :inverse-video nil :overline nil :slant normal :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#93a1a1" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#268bd2" :background "#ffffff"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) nil)))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:inherit org-meta-line :underline t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:inherit org-meta-line :overline t))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#657b83" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#268bd2" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#859900"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#cb4b16" :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900" :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.15))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :height 1.1))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#b58900" :underline t))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#93a1a1" :slant italic))))
 '(org-macro ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#268bd2" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#93a1a1" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#2aa198" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#b58900" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#cb4b16" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#b58900"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#ffffff" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#ffffff" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#dc322f" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#657b83"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#586e75" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#d33682" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#dc322f"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#cb4b16" :height 1.3))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900" :height 1.2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2" :height 1.15))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#b58900" :height 1.1))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#2aa198"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#859900"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#dc322f"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#268bd2"))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#657b83"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#b58900" :foreground "#ffffff"))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#657b83"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:background "#268bd2" :foreground "#ffffff"))))
 '(popup-menu-selection-face ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#ffffff"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#93a1a1"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#586e75"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#657b83"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#657b83" :background "#ffffff" :inverse-video t))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#6c71c4" :weight bold))))
 '(sh-escaped-newline ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "#b58900" :weight bold))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#d33682" :background unspecified :weight bold))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#dc322f" :weight bold))))
 '(solaire-default-face ((((class color) (min-colors 89)) (:inherit default :background "#f57aeefadbfa"))))
 '(solaire-minibuffer-face ((((class color) (min-colors 89)) (:inherit default :background "#f57aeefadbfa"))))
 '(solaire-line-number-face ((((class color) (min-colors 89)) (:inherit (line-number solaire-default-face) :background "#f57aeefadbfa"))))
 '(solaire-hl-line-face ((((class color) (min-colors 89)) (:inherit hl-line :background "#eebfe8b1d5b2"))))
 '(solaire-org-hide-face ((((class color) (min-colors 89)) (:inherit org-hide :background "#f57aeefadbfa"))))
 '(solaire-mode-line-face ((((class color) (min-colors 89)) (:inherit default :background "#ffffff"))))
 '(solaire-mode-line-inactive-face ((((class color) (min-colors 89)) (:inherit default :background "#ffffff"))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(sp-wrap-overlay-face ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(sp-wrap-tag-overlay-face ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(sp-show-pair-enclosing ((((class color) (min-colors 89)) (:inherit highlight))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:background unspecified :foreground "#d33682" :weight bold))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#dc322f" :weight bold))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:background "#ffffff"))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#586e75"))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#b58900"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#876d26" :inherit variable-pitch))))
 '(transient-heading ((t (:foreground "#b58900" :weight bold))))
 '(transient-key ((t (:foreground "#586e75" :weight bold))))
 '(transient-argument ((t (:foreground "#2aa198" :weight bold))))
 '(transient-value ((t (:foreground "#2aa198" :weight bold))))
 '(transient-inactive-argument ((t (:foreground "#93a1a1" :weight normal))))
 '(transient-inactive-value ((t (:foreground "#93a1a1" :weight normal))))
 '(transient-unreachable ((t (:foreground "#93a1a1" :weight normal))))
 '(transient-unreachable-key ((t (:foreground "#93a1a1" :weight normal))))
 '(transient-enabled-suffix ((t (:foreground "#ffffff" :background "#859900" :weight bold))))
 '(transient-disabled-suffix ((t (:foreground "#ffffff" :background "#dc322f" :weight bold))))
 '(transient-nonstandard-key ((t (:underline nil :background "#ffffff"))))
 '(transient-mismatched-key ((t (:underline nil :background "#ffffff"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#93a1a1" :background "#ffffff"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#268bd2" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#586e75" :background "#ffffff" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background unspecified :foreground "#93a1a1" :inverse-video unspecified :slant italic))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background unspecified :foreground "#586e75" :inverse-video unspecified))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#dc322f" :inverse-video t))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background unspecified :foreground "#93a1a1" :inverse-video unspecified))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background unspecified :foreground "#fb7640" :inverse-video t))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background unspecified :foreground "#d33682" :inverse-video unspecified))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#ff6849" :foreground unspecified :inverse-video unspecified))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background unspecified :foreground "#b58900" :inverse-video unspecified :weight bold))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background unspecified :foreground "#ff6849" :inverse-video t))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#cb4b16" :inverse-video t :weight bold))))
 '(yas-field-highlight-face ((((class color) (min-colors 89)) (:inherit secondary-selection))))
 '(default ((t (:background "white" :foreground "#657b83")))))

(provide-theme 'solarized-light-white)
